# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

name: ðŸ› Bug Report
# title: " "
description: Problems with Ultralytics software
labels: [bug, triage]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an Ultralytics ðŸ› Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the Ultralytics [Docs](https://docs.ultralytics.com/) and [issues](https://github.com/ultralytics/PROJECT_NAME/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the Ultralytics [issues](https://github.com/ultralytics/PROJECT_NAME/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: Ultralytics Component
      description: |
        Please select the component where you found the bug.
      multiple: true
      options:
        - "Install"
        - "Setup"
        - "Configuration"
        - "CLI"
        - "API"
        - "Training"
        - "Validation"
        - "Prediction"
        - "Export"
        - "Integration"
        - "Documentation"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Please provide as much information as possible. Copy and paste console output and error messages including the _full_ traceback. Use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to format text, code and logs. If necessary, include screenshots for visual elements only. Providing detailed information will help us resolve the issue more efficiently.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please provide your system information to help us diagnose the problem.
      placeholder: |
        Please include:
        - OS (e.g., Ubuntu 20.04, macOS 13.5, Windows 11)
        - Python version (e.g., 3.11.2)
        - Package version (e.g., pip list | grep ultralytics)
        - Hardware (e.g., CPU, GPU model)
        - Any relevant environment details

        Example:
        ```
        OS: macOS-13.5.2
        Python: 3.11.2
        Package: ultralytics==8.3.2
        Hardware: Apple M3, 16GB RAM
        Environment: Terminal
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimal reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/).
      placeholder: |
        ```python
        # Code to reproduce your issue here
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ultralytics/PROJECT_NAME/pulls) (PR) to help improve Ultralytics software for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the Ultralytics [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
