# Ultralytics 🚀, AGPL-3.0 license
# Ultralytics format action

name: Ultralytics Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo Git Branch Information
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "Current branch is $(git branch --show-current)"
      - uses: ultralytics/action@dev
